### ISSUE TITLE
Default value

### ISSUE THREAD

**Issue by ak04nv** [coleifer/wtf-peewee#26]
I use wtf-peewee in my flask application and I found nice issue. Actually this is not a bug.
```python
    form = ModelForm(request.form)
    if form.validate():
        obj = Model(**form.data)
        obj.active = True  # WTForms issue?
        obj.save()
```
In my case POST data form hasn't `active` field and the `validate()` method of the `form` sets the `False` value to the same attribute of object. But in my peewee model this field has a `True` value as default in database schema.
Keep it in mind ;-)

**Comment by coleifer** [comment]
What would you propose here? Is there a fix you'd like to see?

**Comment by ak04nv** [comment]
I would like to save in database the object with default values for fields which have no data in post request. Is it possible?

**Comment by coleifer** [comment]
Peewee models support default values for fields. Here's the documentation: http://docs.peewee-orm.com/en/latest/peewee/models.html#default-field-values
