### ISSUE TITLE
No field from mixin

### ISSUE THREAD

**Issue by ak04nv** [coleifer/wtf-peewee#28]
If I'll create a model with mixin like this:
```python
class WithOldID:
    old_id = peewee.IntegerField(default=0, verbose_name='Old ID')

class Branch(WithOldID, db.Model):
    name = peewee.CharField(max_length=10)
    code = peewee.CharField(max_length=10, unique=True)
    active = peewee.BooleanField(default=True)
```

and make a form from this model:
```python
BranchForm = model_form(Branch)
```

this form will not have an `old_id` attribute because `model._meta.get_sorted_fields()` method returns a list without this field. Not sure what package owns an issue: peewee or wtf-peewee.

**Comment by coleifer** [comment]
At the moment the way to do this would be to make `WithOldID` a model as well, even if you don't plan to use it as an actual database model.

```python
class WithOldID(db.Model):
    old_id = peewee.IntegerField(default=0, verbose_name='Old ID')

class Branch(WithOldID, db.Model):
    name = peewee.CharField(max_length=10)
    code = peewee.CharField(max_length=10, unique=True)
    active = peewee.BooleanField(default=True)
```
