### ISSUE TITLE
IPField, Autofield, UUIDField not found

### ISSUE THREAD

**Issue by shayneoAtNorwood** [coleifer/wtf-peewee#38]
Hi there. I'm running a short stack that uses flask, flask-admin, peewee and thus wtf-peewee

Due to the fact flask-admin does not yet support peewee 3.0 (I think its only a one liner in flask-admin) I've had to downgrade peewee to the 2.x branch. 

Anyway, it seems that wtf-peewee is expecting IPField, Autofield and UUIDField to be there and these dont seem to exist in peewee. I'm not sure if its a 2.x thing, or an SQLite thing, but as a stopgap I've commented these out in the peewee-wtf library , but obviously hand-patching site-packages isnt exactly a sustainable way to fly (Particularly as I want to deploy this to a few servers)

Is there a better solution to this?

**Comment by coleifer** [comment]
If you're using Peewee 2.x, you'll want to downgrade wtf-peewee to the version prior to 3.0.

**Comment by shayneoAtNorwood** [comment]
You might want to update the requirements for PyPi then, as this would normally be detected by pip and adjusted for or flagged

**Comment by shayneoAtNorwood** [comment]
my bad, looks like it is. I wonder why this wasnt picked up by pip?
