### ISSUE TITLE
Missing attribute/method on generated object

### ISSUE THREAD

**Issue by kpoman** [coleifer/wtf-peewee#41]
I am trying to use the lib with Flask-Bootstrap and Flask-WTF and am getting this error:

>     {{ wtf.quick_form(form) }}
>   File "/usr/local/lib/python3.6/dist-packages/jinja2/runtime.py", line 579, in _invoke
>     rv = self._func(*arguments)
>   File "/usr/local/lib/python3.6/dist-packages/flask_bootstrap/templates/bootstrap/wtf.html", line 200, in template
>     {{ form.hidden_tag() }}
> jinja2.exceptions.UndefinedError: 'wtfpeewee.orm.JewelerForm object' has no attribute 'hidden_tag'
> 

Apparently bootstrap's wtf macros do need a hidden_tag method for generating some csrf stuff, which is not populated on the form model built with this lib.

**Comment by coleifer** [comment]
This project has nothing to do with flask-wtf or flask-bootstrap.
