### ISSUE TITLE
"Fix" python 3 support

### ISSUE THREAD

**Issue by ibushong** [coleifer/wtf-peewee#51]
I'm using [caniusepython3](https://github.com/brettcannon/caniusepython3) to help with migrating a project, and it indicates that `wtf-peewee` is not python 3 compatible, though I believe it is, right? It sounds like the classifiers in `setup.py` just need to be updated. Not critical of course, but would be nice.

**Comment by coleifer** [comment]
here ya go

**Comment by ibushong** [comment]
Thanks!
