### ISSUE TITLE
ImportError: cannot import name 'HTMLString' from 'wtforms.widgets' in wtfpeewee/fields.py

### ISSUE THREAD

**Issue by mhsundstrom** [coleifer/wtf-peewee#55]
I am using Flask-Admin per your notice that flask-peewee is now in maintenance-only mode. I encountered the above-mentioned error importing ModelBase from flask_admin.contrib.peewee.

Some searching found that wtforms had replaced HTMLString with the use of Markupsafe.Markup, per their Pull Request #400, as of version 2.3.0 on 2020-04-21.

A quick patch of my code, substituting an import and use of Markup instead of HTMLString, seems to work in my preliminary testing.

I am not well-versed in producing Pull Requests, so I hope this information is sufficient. Thanks!

**Comment by coleifer** [comment]
3.0.3 released.
